send_magic_packet:
  name: Send magic packet
  description: Send a 'magic packet' to wake up a device with 'Wake-On-LAN' capabilities.
  fields:
    mac:
      name: MAC address
      description: MAC address of the device to wake up.
      required: true
      example: "aa:bb:cc:dd:ee:ff"
      selector:
        text:
    broadcast_address:
      name: Broadcast address
      description: Broadcast IP where to send the magic packet.
      example: 192.168.255.255
      selector:
        text:
    broadcast_port:
      name: Broadcast port
      description: Port where to send the magic packet.
      default: 9
      selector:
        number:
          min: 1
          max: 65535
restart_to_windows_from_linux:
  name: Restart to Windows from Linux
  description: Restart the computer to Windows when running Linux using Grub.
  target:
    device:
      integration: easy_computer_manage
restart_to_linux_from_windows:
  name: Restart to Linux from Windows
  description: Restart the computer to Linux when running Windows.
  target:
    device:
      integration: easy_computer_manage
start_computer_to_windows:
  name: Start computer to Windows
  description: Start the computer directly Windows (boots to Linux, set grub reboot, then boots to Windows).
  target:
    device:
      integration: easy_computer_manage
put_computer_to_sleep:
  name: Put computer to sleep
  description: Put the computer to sleep.
  target:
    device:
      integration: easy_computer_manage
restart_computer:
  name: Restart
  description: Restart the computer.
  target:
    device:
      integration: easy_computer_manage
change_monitors_config:
  name: Change monitors config
  description: Change monitors config.
  fields:
    monitors_config:
      name: Monitors config
      description: Monitors config.
      required: true
      selector:
        text:
  target:
    device:
      integration: easy_computer_manage